// Generated by CoffeeScript 1.6.3
(function() {
  var fs;

  fs = require('fs');

  fs.readdir(__dirname, function(err, contents) {
    if (err) {
      throw err;
    }
    return contents.forEach(function(content) {
      var path;
      path = "./" + content;
      return fs.stat(path, function(err, stat) {
        if (err) {
          throw err;
        }
        if (stat.isFile()) {
          return console.log("" + content + " " + stat.size + " bytes");
        }
      });
    });
  });

}).call(this);
