// Generated by CoffeeScript 1.6.3
(function() {
  var fs, lerDiretorio;

  fs = require('fs');

  lerDiretorio = function() {
    var ler;
    fs.readdir(__dirname, function(err, diretorio) {
      if (err) {
        throw err;
      }
      return diretorio.forEach(function(arquivo) {
        return ler(arquivo);
      });
    });
    return ler = function(arquivo) {
      var path;
      path = "./" + arquivo;
      return fs.stat(path, function(err, stat) {
        if (err) {
          throw err;
        }
        if (stat.isFile()) {
          return console.log("" + arquivo + " " + stat.size + " bytes");
        }
      });
    };
  };

  lerDiretorio();

}).call(this);
