// Generated by CoffeeScript 1.6.3
(function() {
  var fs, leituraSync;

  fs = require('fs');

  leituraSync = function(arquivo) {
    var fim, inicio;
    console.log('Leitura Sync');
    inicio = new Date().getTime();
    fs.readFileSync(arquivo);
    fim = new Date().getTime();
    return console.log("Bloquei síncrono " + (fim - inicio) + " ms");
  };

  module.exports = leituraSync;

}).call(this);
